name: Build container and deploy
on:
  push:
    branches:
      - 'main'
      - 'feature/dockerize' # temporary
    tags:
      - 'v*'

jobs:
  docker-build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: generate docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: Contest-Result-Analyser/backend
          tags: |
            type=ref,event=branch=^(main|feature/dockerize)$,enable=true,name=dev
            type=ref,event=tag,enable=true,name=latest
            type=ref,event=tag,enable=true
          
          labels: |
            org.opencontainers.image.title=Contest Result Analyzer
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
      
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}